/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// CreateWorkflowTransitionRule : A workflow transition rule.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CreateWorkflowTransitionRule {
    /// The type of the transition rule.
    #[serde(rename = "type")]
    pub _type: String,
    /// EXPERIMENTAL. The configuration of the transition rule.
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<::std::collections::HashMap<String, serde_json::Value>>,
}

impl CreateWorkflowTransitionRule {
    /// A workflow transition rule.
    pub fn new(_type: String) -> CreateWorkflowTransitionRule {
        CreateWorkflowTransitionRule {
            _type,
            configuration: None,
        }
    }
}
