/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// CustomFieldContextDefaultValueDate : The default value for a Date custom field.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomFieldContextDefaultValueDate {
    /// The default date in ISO format. Ignored if `useCurrent` is true.
    #[serde(rename = "date", skip_serializing_if = "Option::is_none")]
    pub date: Option<String>,
    /// Whether to use the current date.
    #[serde(rename = "useCurrent", skip_serializing_if = "Option::is_none")]
    pub use_current: Option<bool>,
    #[serde(rename = "type")]
    pub _type: String,
}

impl CustomFieldContextDefaultValueDate {
    /// The default value for a Date custom field.
    pub fn new(_type: String) -> CustomFieldContextDefaultValueDate {
        CustomFieldContextDefaultValueDate {
            date: None,
            use_current: None,
            _type,
        }
    }
}
