/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// CustomFieldContextDefaultValueForgeObjectField : The default value for a Forge object custom field.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomFieldContextDefaultValueForgeObjectField {
    /// The default JSON object.
    #[serde(rename = "object", skip_serializing_if = "Option::is_none")]
    pub object: Option<serde_json::Value>,
    #[serde(rename = "type")]
    pub _type: String,
}

impl CustomFieldContextDefaultValueForgeObjectField {
    /// The default value for a Forge object custom field.
    pub fn new(_type: String) -> CustomFieldContextDefaultValueForgeObjectField {
        CustomFieldContextDefaultValueForgeObjectField {
            object: None,
            _type,
        }
    }
}


