/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// CustomFieldContextDefaultValueForgeMultiUserField : Defaults for a Forge collection of users custom field.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomFieldContextDefaultValueForgeMultiUserField {
    /// The ID of the context.
    #[serde(rename = "contextId")]
    pub context_id: String,
    /// The IDs of the default users.
    #[serde(rename = "accountIds")]
    pub account_ids: Vec<String>,
}

impl CustomFieldContextDefaultValueForgeMultiUserField {
    /// Defaults for a Forge collection of users custom field.
    pub fn new(
        context_id: String,
        account_ids: Vec<String>,
    ) -> CustomFieldContextDefaultValueForgeMultiUserField {
        CustomFieldContextDefaultValueForgeMultiUserField {
            context_id,
            account_ids,
        }
    }
}
