/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// CustomFieldContextDefaultValueForgeGroupField : The default value for a Forge group custom field.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomFieldContextDefaultValueForgeGroupField {
    /// The ID of the context.
    #[serde(rename = "contextId")]
    pub context_id: String,
    /// The ID of the the default group.
    #[serde(rename = "groupId")]
    pub group_id: String,
}

impl CustomFieldContextDefaultValueForgeGroupField {
    /// The default value for a Forge group custom field.
    pub fn new(
        context_id: String,
        group_id: String,
    ) -> CustomFieldContextDefaultValueForgeGroupField {
        CustomFieldContextDefaultValueForgeGroupField {
            context_id,
            group_id,
        }
    }
}
