/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// CustomFieldContextDefaultValueForgeNumberField : Default value for a Forge number custom field.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct CustomFieldContextDefaultValueForgeNumberField {
    /// The default floating-point number.
    #[serde(rename = "number")]
    pub number: f64,
}

impl CustomFieldContextDefaultValueForgeNumberField {
    /// Default value for a Forge number custom field.
    pub fn new(number: f64) -> CustomFieldContextDefaultValueForgeNumberField {
        CustomFieldContextDefaultValueForgeNumberField { number }
    }
}
