/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// DashboardGadgetResponse : The list of gadgets on the dashboard.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DashboardGadgetResponse {
    /// The list of gadgets.
    #[serde(rename = "gadgets")]
    pub gadgets: Vec<crate::models::DashboardGadget>,
}

impl DashboardGadgetResponse {
    /// The list of gadgets on the dashboard.
    pub fn new(gadgets: Vec<crate::models::DashboardGadget>) -> DashboardGadgetResponse {
        DashboardGadgetResponse { gadgets }
    }
}
