/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// JqlQueriesToSanitize : The list of JQL queries to sanitize for the given account IDs.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct JqlQueriesToSanitize {
    /// The list of JQL queries to sanitize. Must contain unique values. Maximum of 20 queries.
    #[serde(rename = "queries")]
    pub queries: Vec<crate::models::JqlQueryToSanitize>,
}

impl JqlQueriesToSanitize {
    /// The list of JQL queries to sanitize for the given account IDs.
    pub fn new(queries: Vec<crate::models::JqlQueryToSanitize>) -> JqlQueriesToSanitize {
        JqlQueriesToSanitize { queries }
    }
}
