/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// License : Details about a license for the Jira instance.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct License {
    /// The applications under this license.
    #[serde(rename = "applications")]
    pub applications: Vec<crate::models::LicensedApplication>,
}

impl License {
    /// Details about a license for the Jira instance.
    pub fn new(applications: Vec<crate::models::LicensedApplication>) -> License {
        License { applications }
    }
}
