/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct LinkIssueRequestJsonBean {
    #[serde(rename = "type")]
    pub _type: crate::models::IssueLinkType,
    #[serde(rename = "inwardIssue")]
    pub inward_issue: crate::models::LinkedIssue,
    #[serde(rename = "outwardIssue")]
    pub outward_issue: crate::models::LinkedIssue,
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<crate::models::Comment>,
}

impl LinkIssueRequestJsonBean {
    pub fn new(_type: crate::models::IssueLinkType, inward_issue: crate::models::LinkedIssue, outward_issue: crate::models::LinkedIssue) -> LinkIssueRequestJsonBean {
        LinkIssueRequestJsonBean {
            _type: _type,
            inward_issue: inward_issue,
            outward_issue: outward_issue,
            comment: None,
        }
    }
}


