/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// ProjectIssueSecurityLevels : List of issue level security items in a project.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct ProjectIssueSecurityLevels {
    /// Issue level security items list.
    #[serde(rename = "levels")]
    pub levels: Vec<crate::models::SecurityLevel>,
}

impl ProjectIssueSecurityLevels {
    /// List of issue level security items in a project.
    pub fn new(levels: Vec<crate::models::SecurityLevel>) -> ProjectIssueSecurityLevels {
        ProjectIssueSecurityLevels { levels }
    }
}
