/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// SanitizedJqlQuery : Details of the sanitized JQL query.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SanitizedJqlQuery {
    /// The initial query.
    #[serde(rename = "initialQuery", skip_serializing_if = "Option::is_none")]
    pub initial_query: Option<String>,
    /// The sanitized query, if there were no errors.
    #[serde(rename = "sanitizedQuery", skip_serializing_if = "Option::is_none")]
    pub sanitized_query: Option<String>,
    /// The list of errors.
    #[serde(rename = "errors", skip_serializing_if = "Option::is_none")]
    pub errors: Option<crate::models::ErrorCollection>,
    /// The account ID of the user for whom sanitization was performed.
    #[serde(rename = "accountId", skip_serializing_if = "Option::is_none")]
    pub account_id: Option<String>,
}

impl SanitizedJqlQuery {
    /// Details of the sanitized JQL query.
    pub fn new() -> SanitizedJqlQuery {
        SanitizedJqlQuery {
            initial_query: None,
            sanitized_query: None,
            errors: None,
            account_id: None,
        }
    }
}


