/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// SearchAutoCompleteFilter : Details of how to filter and list search auto complete information.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SearchAutoCompleteFilter {
    /// List of project IDs used to filter the visible field details returned.
    #[serde(rename = "projectIds", skip_serializing_if = "Option::is_none")]
    pub project_ids: Option<Vec<i64>>,
    /// Include collapsed fields for fields that have non-unique names.
    #[serde(
        rename = "includeCollapsedFields",
        skip_serializing_if = "Option::is_none"
    )]
    pub include_collapsed_fields: Option<bool>,
}

impl SearchAutoCompleteFilter {
    /// Details of how to filter and list search auto complete information.
    pub fn new() -> SearchAutoCompleteFilter {
        SearchAutoCompleteFilter {
            project_ids: None,
            include_collapsed_fields: None,
        }
    }
}
