/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// UpdateFieldConfigurationSchemeDetails : The details of the field configuration scheme.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UpdateFieldConfigurationSchemeDetails {
    /// The name of the field configuration scheme. The name must be unique.
    #[serde(rename = "name")]
    pub name: String,
    /// The description of the field configuration scheme.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl UpdateFieldConfigurationSchemeDetails {
    /// The details of the field configuration scheme.
    pub fn new(name: String) -> UpdateFieldConfigurationSchemeDetails {
        UpdateFieldConfigurationSchemeDetails {
            name,
            description: None,
        }
    }
}
