/*
 * The Jira Cloud platform REST API
 *
 * Jira Cloud platform REST API documentation
 *
 * The version of the OpenAPI document: 1001.0.0-SNAPSHOT
 * Contact: ecosystem@atlassian.com
 * Generated by: https://openapi-generator.tech
 */

/// WorkflowRules : A collection of transition rules.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct WorkflowRules {
    #[serde(rename = "conditionsTree", skip_serializing_if = "Option::is_none")]
    pub conditions_tree: Option<crate::models::WorkflowCondition>,
    /// The workflow validators.
    #[serde(rename = "validators", skip_serializing_if = "Option::is_none")]
    pub validators: Option<Vec<crate::models::WorkflowTransitionRule>>,
    /// The workflow post functions.
    #[serde(rename = "postFunctions", skip_serializing_if = "Option::is_none")]
    pub post_functions: Option<Vec<crate::models::WorkflowTransitionRule>>,
}

impl WorkflowRules {
    /// A collection of transition rules.
    pub fn new() -> WorkflowRules {
        WorkflowRules {
            conditions_tree: None,
            validators: None,
            post_functions: None,
        }
    }
}


